
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-12
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwOTE2MDI3","is_bot":false,"login":"jzipkin1812","name":"Javin Zipkin"},"headRefName":"javin-editAnnouncements","number":35,"title":"Javin - Overhauled/refactored the CRUD operation for editing announcements","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/35"},{"author":{"id":"U_kgDOB8qFSg","is_bot":false,"login":"yixuan-wong","name":""},"headRefName":"yx-fixedPost","number":34,"title":"yx - Fixed Create Announcements Post","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/34"},{"author":{"id":"U_kgDOB8qFSg","is_bot":false,"login":"yixuan-wong","name":""},"headRefName":"yx-createAnnouncementsPage","number":28,"title":"yx - Created Create Announcements Page and changed page header to show the…","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/28"},{"author":{"id":"U_kgDOB8qFRw","is_bot":false,"login":"Abby-Fan04","name":""},"headRefName":"Abby-issue16","number":27,"title":"Issue 16 - Change link of Mattanjah de Vries in footer","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/27"},{"author":{"id":"U_kgDOCEgVBw","is_bot":false,"login":"yungongWang","name":""},"headRefName":"yungong_BuySell","number":23,"title":"Yungong - UX fix, changing buy/sell into title case","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/23"},{"author":{"id":"MDQ6VXNlcjMwOTE2MDI3","is_bot":false,"login":"jzipkin1812","name":"Javin Zipkin"},"headRefName":"javin-profitsFrame","number":21,"title":"Fixed visual ugliness on profits table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/21"},{"author":{"id":"MDQ6VXNlcjMwOTE2MDI3","is_bot":false,"login":"jzipkin1812","name":"Javin Zipkin"},"headRefName":"javin-sortingBug","number":20,"title":"Sort by leaderbord wealth bug fix","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/20"}]
