
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-12
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-12
pull_requests: [{"author":{"id":"U_kgDOCEgVBw","is_bot":false,"login":"yungongWang","name":""},"headRefName":"yungong_CommonsPlayTest","number":57,"title":"yungong - try to add CommonsPlay exception test","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/57"},{"author":{"id":"U_kgDOB8qFRw","is_bot":false,"login":"Abby-Fan04","name":""},"headRefName":"Abby-getbyStudentId","number":54,"title":"Abby get individual students by studentId","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/54"},{"author":{"id":"U_kgDOCEgVBw","is_bot":false,"login":"yungongWang","name":""},"headRefName":"yungong_ManageCowsTest","number":51,"title":"yungong - try to add tests for ManageCows","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/51"},{"author":{"id":"MDQ6VXNlcjMwNjMzMDE5","is_bot":false,"login":"mayarosenbaum","name":""},"headRefName":"mr-ourTable-testing","number":50,"title":"Mr-OurTable testing - Reduced runtime and maintained testing accuracy","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/50"},{"author":{"id":"U_kgDOCEgVBw","is_bot":false,"login":"yungongWang","name":""},"headRefName":"yungong_restore","number":49,"title":"Yungong - displaying announcement table on play page updated","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/49"},{"author":{"id":"U_kgDOB8qFRw","is_bot":false,"login":"Abby-Fan04","name":""},"headRefName":"Abby-GETandCSVupload","number":47,"title":"Abby-Add in Get_ALL function to Student and add function to upload roaster on student","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/47"}]
