
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-12
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-12
pull_requests: [{"author":{"id":"U_kgDOCEgVBw","is_bot":false,"login":"yungongWang","name":""},"headRefName":"yungong_BuySell","number":23,"title":"Yungong - UX fix, changing buy/sell into title case","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/23"},{"author":{"id":"U_kgDOB8qFSg","is_bot":false,"login":"yixuan-wong","name":""},"headRefName":"yx-explanationFix","number":22,"title":"Minor UX Fix - made explanation of buying and selling cows neater","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/22"},{"author":{"id":"MDQ6VXNlcjMwOTE2MDI3","is_bot":false,"login":"jzipkin1812","name":"Javin Zipkin"},"headRefName":"javin-profitsFrame","number":21,"title":"Fixed visual ugliness on profits table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/21"},{"author":{"id":"MDQ6VXNlcjMwOTE2MDI3","is_bot":false,"login":"jzipkin1812","name":"Javin Zipkin"},"headRefName":"javin-sortingBug","number":20,"title":"Sort by leaderbord wealth bug fix","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-12/pull/20"}]
